### ISSUE TITLE
Why are certs unsigned? 

### ISSUE THREAD

**Issue by Javaman2** [TooTallNate/node-agent-base#44] opened 2020-07-02 17:34 UTC
Just wondering why the certs are unsigned?

**Comment by TooTallNate** [comment] 2020-07-02 20:01
Which certs?

**Comment by Javaman2** [comment] 2020-07-02 22:16
[These certs](https://github.com/TooTallNate/node-agent-base/tree/master/test) are being flagged in my Angular compile. So I thought I'd ask you about them.

**Comment by TooTallNate** [comment] 2020-07-02 23:21
Right, they're self-signed certs for use with the tests. They should not be included in the npm package though, which version of `agent-base` are you using?

**Comment by TooTallNate** [comment] 2020-07-02 23:22
See https://github.com/TooTallNate/node-agent-base/issues/34 which is more or less a duplicate of this one.

**Closed by TooTallNate** 2020-07-02 23:22 UTC

**Comment by Javaman2** [comment] 2020-07-03 23:07
Thanks TooTall!
